apiVersion: v1
data:
  cacert: 
  clouds.yaml: Y2xvdWRzOgogIG1qOgogICAgYXV0aDoKICAgICAgYXV0aF91cmw6IGh0dHA6Ly9rZXlzdG9uZS1hcGkub3BlbnN0YWNrLnN2Yy5jbHVzdGVyLmxvY2FsL3YzCiAgICAgIHVzZXJuYW1lOiBhZG1pbgogICAgICBwYXNzd29yZDogRWFzeUNsb3VkQEVTMjAxOCEKICAgICAgcHJvamVjdF9uYW1lOiBhZG1pbgogICAgICB1c2VyX2RvbWFpbl9uYW1lOiBEZWZhdWx0CiAgICAgIHByb2plY3RfZG9tYWluX25hbWU6IERlZmF1bHQKICAgIHJlZ2lvbl9uYW1lOiBSZWdpb25PbmUKICAgIGludGVyZmFjZTogYWRtaW4KICAgIGVuZHBvaW50X3R5cGU6IGFkbWluVVJMCiAgICBpZGVudGl0eV9hcGlfdmVyc2lvbjogMwo=
kind: Secret
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move: "true"
  name: mj-cloud-config
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
kind: Config
metadata:
  name: mj-vars-business
data: {}
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
kind: Config
metadata:
  name: mj-vars-fixed
data: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mj-hosts-conf
data:
  inventory.ini: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mj-vars-conf
data:
  vars.yaml: ""
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha1
kind: AnsibleConfigTemplate
metadata:
  name: mj-md-0
spec:
  template:
    spec:
      role:
      - kube-node
      varsConfigRefs:
        business:
          name: mj-vars-business
        fixed:
          name: mj-vars-fixed
      clusterTemplate:
        apiVersion: cluster.kubean.io/v1alpha1
        kind: Cluster
      clusterOperationTemplate:
        apiVersion: clusterops.kubean.io/v1alpha1
        kind: ClusterOperation
        spec:
          image: hub.easystack.cn/captain/launcher-captain:dev
          actionType: playbook
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
kind: AnsibleControlPlane
metadata:
  name: mj-control-plane
spec:
  replicas: 1
  version: v1.26.4-es
  machineTemplate:
    spec:
      clusterName: mj
      bootstrap: {}
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: OpenStackMachineTemplate
        name: mj-control-plane
  ansibleConfigSpec:
    role:
    - kube-master
    - etcd
    varsConfigRefs:
      business:
        name: mj-vars-business
      fixed:
        name: mj-vars-fixed
    clusterTemplate:
      apiVersion: cluster.kubean.io/v1alpha1
      kind: Cluster
    clusterOperationTemplate:
      apiVersion: clusterops.kubean.io/v1alpha1
      kind: ClusterOperation
      spec:
        image: hub.easystack.cn/captain/launcher-captain:dev
        actionType: playbook
---
apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: mj
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    serviceDomain: cluster.local
  controlPlaneRef:
    apiGroup: controlplane.cluster.x-k8s.io
    kind: AnsibleControlPlane
    name: mj-control-plane
  infrastructureRef:
    apiGroup: infrastructure.cluster.x-k8s.io
    kind: OpenStackCluster
    name: mj
---
apiVersion: cluster.x-k8s.io/v1beta2
kind: MachineDeployment
metadata:
  name: mj-md-0
spec:
  clusterName: mj
  replicas: 1
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiGroup: bootstrap.cluster.x-k8s.io
          kind: AnsibleConfigTemplate
          name: mj-md-0
      clusterName: mj
      failureDomain: default-az
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: OpenStackMachineTemplate
        name: mj-md-0
      version: v1.26.4-es
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackCluster
metadata:
  name: mj
spec:
  apiServerLoadBalancer:
    enabled: true
  extensions:
    networking:
      kubeNetworkPlugin: cilium
  externalNetwork:
    id: bbf5eebf-1c7d-4350-b806-a464fa16ec31
  identityRef:
    cloudName: mj
    name: mj-cloud-config
  managedSecurityGroups:
    allNodesSecurityGroupRules:
    - description: Created by cluster-api-provider-openstack - BGP (calico)
      direction: ingress
      etherType: IPv4
      name: BGP (Calico)
      portRangeMax: 179
      portRangeMin: 179
      protocol: tcp
      remoteManagedGroups:
      - controlplane
      - worker
    - description: Created by cluster-api-provider-openstack - IP-in-IP (calico)
      direction: ingress
      etherType: IPv4
      name: IP-in-IP (Calico)
      protocol: "4"
      remoteManagedGroups:
      - controlplane
      - worker
  managedSubnets:
  - cidr: 10.6.0.0/24
    dnsNameservers:
    - 8.8.8.8
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: mj-control-plane
spec:
  template:
    spec:
      flavor: 4c8G
      image:
        filter:
          name: eks-kylin-x86_64-150G.raw
      sshKeyName: mj
      extensions:
        networkInterfaces:
          keepalived: eth0
        loadBalancers:
          controlPlaneVIP: true

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: mj-md-0
spec:
  template:
    spec:
      flavor: 4c8G
      image:
        filter:
          name: eks-kylin-x86_64-150G.raw
      sshKeyName: mj
      extensions:
        networkInterfaces:
          keepalived: eth0
      extensions:
        loadBalancers:
          ingressVIP: true
